name: Ping Monitors

on:
  schedule:
    - cron: "*/1 * * * *"

  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Call StatusPing Cron
        run: |
          curl https://statusping-lyart.vercel.app/api/cron/ping
